version: '2'
services:

  streaming-server:
    build: ../..
    image: codeworksio/streaming-server
    container_name: streaming-server
    volumes:
      - ../../data/var/lib/streaming:/var/lib/streaming
    ports:
      - "1935:1935"
      - "8080:8080"

  streaming-consumer:
    image: codeworksio/nginx
    container_name: streaming-consumer
    volumes:
      - .:/var/www:ro
    ports:
      - "9999:8080"
